import { Metadata } from 'next'
import React from 'react'


export const metadata:Metadata = {
  title: 'Blogs',
  description: 'Generated by create next app',
}

const BlogLayout = ({
  children,
}: {
  children: React.ReactNode
}) => {
  return (
    <div className='mainContent'>
    
      {children}
    </div>
  )
}

export default BlogLayout
