

import { Footer, Navbar } from "@/components";
import "./globals.css";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/context/ThemeContext";


import { Metadata } from "next";
import Head from "next/head";
import AuthProvider from "@/components/authProvider/AuthProvider";
import StoreProvider from "@/components/provider/StoreProvider";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Full Stack Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <html lang="en">
        <ThemeProvider>
          <AuthProvider>
          <StoreProvider>
            <body className={`theme dark container`}>
              <Navbar />
              {children}
              <Footer />
            </body>
            </StoreProvider>
          </AuthProvider>
        </ThemeProvider>
      </html>
    </>
  );
}
